### ISSUE TITLE
A nested object in array is not converted

### ISSUE THREAD

**Issue by jyane** [hiroppy/convert-keys#3]
Hi, abouthiroppy.
Thank you for your 'convert-keys'. This is a great library.

I’ve read your ‘convert-keys’ codes and noticed that a nested object test will fail.
Is this a spec or bug?
This is an example of re-produce for this issue.

``` js
test('should return object as coverted camel case', async (t) => {
  const obj = {
    'hoge_fuga': 1,
    'hogeHoge': {
      'piyo_piyo': 'aaaa',
      'fuga_fuga': 'bbbb'
    },
    'piyo_array': [{ 'foo_bar': 'a'}, {'foo_bar': 'b' }]
  };

  const res = {
    hogeFuga: 1,
    hogeHoge: {
      piyoPiyo: 'aaaa',
      fugaFuga: 'bbbb'
    },
    piyoArray: [{ fooBar: 'a'}, {fooBar: 'b' }] // will fail here
  };

  t.deepEqual(convertKeys.toCamel(obj), res);
});
```

**Comment by jyane** [comment]
If this issue is a bug and you have no time for fix this bug, I will create a pull request for fix.
I want to contribute :-)

**Comment by hiroppy** [comment]
Thank you for reporting.
Good catch. This is a bug;(

@jyane Cool 😎  Go ahead!
